import { Excipient } from '../types';

export const INITIAL_EXCIPIENTS: Excipient[] = [
  {
    id: 'exc-lactose-mono',
    name: 'Lactose Monohydrate',
    casNumber: '64044-51-5',
    smiles: 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O',
    formula: 'C12H22O11.H2O',
    category: 'Diluent',
    typicalConcentration: '20 - 80%',
    dosageForms: ['Tablet', 'Capsule', 'Dry Powder Inhaler'],
    reactiveRiskGroups: ['Reducing Sugar', 'Aldehyde equilibrium', 'Hydroxyl'],
    descriptors: {
      mw: 360.31,
      logP: -4.56,
      tpsa: 189.53,
      hbd: 8,
      hba: 11,
      heavyAtoms: 23,
      rotatableBonds: 4,
      fractionCsp3: 1.0,
      ringCount: 2,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Reducing Sugar', 'Hemiacetal', 'Polyol']
    },
    description: 'Widely used diluent and binder. Undergoes Maillard condensation with primary/secondary amines leading to yellow/brown discoloration.'
  },
  {
    id: 'exc-mcc-102',
    name: 'Microcrystalline Cellulose (MCC PH-102)',
    casNumber: '9004-34-6',
    smiles: 'C1C(C(C(C(O1)O)O)O)O',
    formula: '(C6H10O5)n',
    category: 'Binder',
    typicalConcentration: '10 - 90%',
    dosageForms: ['Tablet', 'Capsule', 'Granule'],
    reactiveRiskGroups: ['Non-reducing Carbohydrate', 'Primary Hydroxyl', 'Secondary Hydroxyl'],
    descriptors: {
      mw: 162.14,
      logP: -2.31,
      tpsa: 99.38,
      hbd: 3,
      hba: 5,
      heavyAtoms: 11,
      rotatableBonds: 2,
      fractionCsp3: 1.0,
      ringCount: 1,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Polysaccharide', 'Polyol']
    },
    description: 'Gold-standard direct compression binder and diluent. Highly inert; moisture content must be monitored for hydrolytically unstable APIs.'
  },
  {
    id: 'exc-pvp-k30',
    name: 'Polyvinylpyrrolidone (PVP K30 / Povidone)',
    casNumber: '9003-39-8',
    smiles: 'CC(C1=CC=CC1=O)C',
    formula: '(C6H9NO)n',
    category: 'Binder',
    typicalConcentration: '0.5 - 5%',
    dosageForms: ['Tablet', 'Granule', 'Oral Solution'],
    reactiveRiskGroups: ['Pervasive Peroxides Trace', 'Lactam Amide'],
    descriptors: {
      mw: 111.14,
      logP: -0.24,
      tpsa: 20.31,
      hbd: 0,
      hba: 1,
      heavyAtoms: 8,
      rotatableBonds: 1,
      fractionCsp3: 0.833,
      ringCount: 1,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Cyclic Amide (Lactam)']
    },
    description: 'Versatile wet binder and solubilizer. May contain trace peroxides which degrade oxidation-sensitive active ingredients.'
  },
  {
    id: 'exc-hpmc-k100m',
    name: 'Hypromellose (HPMC K100M)',
    casNumber: '9004-65-3',
    smiles: 'COCC(C)O',
    formula: 'C56H108O30',
    category: 'Coating',
    typicalConcentration: '2 - 5% (Coating), 10 - 80% (Controlled Release)',
    dosageForms: ['Sustained-Release Tablet', 'Film Coated Tablet'],
    reactiveRiskGroups: ['Ether', 'Hydroxyl'],
    descriptors: {
      mw: 1200.0,
      logP: -1.1,
      tpsa: 140.0,
      hbd: 4,
      hba: 8,
      heavyAtoms: 80,
      rotatableBonds: 10,
      fractionCsp3: 1.0,
      ringCount: 3,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Hydroxypropyl Ether', 'Cellulose Ether']
    },
    description: 'Hydrophilic matrix polymer for controlled-release formulations and film coating. High chemical inertness across pH 3-11.'
  },
  {
    id: 'exc-crospovidone',
    name: 'Crospovidone (PVPP)',
    casNumber: '25249-54-1',
    smiles: 'C1CCN(C1=O)C=C',
    formula: '(C6H9NO)n',
    category: 'Disintegrant',
    typicalConcentration: '2 - 5%',
    dosageForms: ['Orally Disintegrating Tablet (ODT)', 'Immediate Release Tablet'],
    reactiveRiskGroups: ['Cross-linked Polymer', 'Trace Peroxides'],
    descriptors: {
      mw: 111.14,
      logP: -0.18,
      tpsa: 20.31,
      hbd: 0,
      hba: 1,
      heavyAtoms: 8,
      rotatableBonds: 0,
      fractionCsp3: 0.667,
      ringCount: 1,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Cross-linked Lactam']
    },
    description: 'Superdisintegrant with rapid wicking and swelling without gel formation. Trace peroxides require monitoring for oxidative drugs.'
  },
  {
    id: 'exc-mannitol',
    name: 'D-Mannitol',
    casNumber: '69-65-8',
    smiles: 'C(C(C(C(C(CO)O)O)O)O)O',
    formula: 'C6H14O6',
    category: 'Diluent',
    typicalConcentration: '10 - 90%',
    dosageForms: ['Chewable Tablet', 'ODT', 'Lyophilized Injectable'],
    reactiveRiskGroups: ['Polyol', 'Non-reducing Sugar Alcohol'],
    descriptors: {
      mw: 182.17,
      logP: -3.1,
      tpsa: 121.38,
      hbd: 6,
      hba: 6,
      heavyAtoms: 12,
      rotatableBonds: 5,
      fractionCsp3: 1.0,
      ringCount: 0,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Sugar Alcohol', 'Hexitol']
    },
    description: 'Non-hygroscopic sugar alcohol diluent with negative heat of solution (cooling taste). Does not undergo Maillard reaction with primary amines.'
  },
  {
    id: 'exc-mg-stearate',
    name: 'Magnesium Stearate',
    casNumber: '557-04-0',
    smiles: 'CCCCCCCCCCCCCCCCCC(=O)[O-].CCCCCCCCCCCCCCCCCC(=O)[O-].[Mg+2]',
    formula: 'C36H70MgO4',
    category: 'Lubricant',
    typicalConcentration: '0.25 - 2%',
    dosageForms: ['Tablet', 'Capsule'],
    reactiveRiskGroups: ['Divalent Metal Cation (Mg2+)', 'Carboxylate Salt', 'Hydrophobic Fatty Acid'],
    descriptors: {
      mw: 591.24,
      logP: 14.2,
      tpsa: 80.26,
      hbd: 0,
      hba: 4,
      heavyAtoms: 41,
      rotatableBonds: 32,
      fractionCsp3: 0.944,
      ringCount: 0,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Fatty Acid Salt', 'Magnesium Carboxylate']
    },
    description: 'Standard boundary lubricant. Divalent Mg2+ can chelate fluoroquinolones, tetracyclines, and interact with basic drugs forming magnesium complexes.'
  },
  {
    id: 'exc-talc',
    name: 'Talc (Purified)',
    casNumber: '14807-96-6',
    smiles: '[Mg+2].[Mg+2].[Mg+2].[O-][Si](=O)[O-].[O-][Si](=O)[O-].[OH-].[OH-]',
    formula: 'Mg3Si4O10(OH)2',
    category: 'Glidant',
    typicalConcentration: '1 - 5%',
    dosageForms: ['Tablet', 'Capsule', 'Dusting Powder'],
    reactiveRiskGroups: ['Inorganic Mineral Hydrate', 'Alkaline Surface Sites'],
    descriptors: {
      mw: 379.27,
      logP: 0.0,
      tpsa: 120.0,
      hbd: 2,
      hba: 10,
      heavyAtoms: 19,
      rotatableBonds: 0,
      fractionCsp3: 0.0,
      ringCount: 0,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Magnesium Silicate Hydrate']
    },
    description: 'Effective glidant and lubricant hydrophobic filler. Extremely chemically inert; surface basicity should be evaluated for acid-labile actives.'
  },
  {
    id: 'exc-aerosil-200',
    name: 'Colloidal Silicon Dioxide (Aerosil 200)',
    casNumber: '112945-52-5',
    smiles: 'O=[Si]=O',
    formula: 'SiO2',
    category: 'Glidant',
    typicalConcentration: '0.1 - 1%',
    dosageForms: ['Tablet', 'Capsule', 'Suspension'],
    reactiveRiskGroups: ['Silanol Groups (Si-OH)', 'High Surface Area Adsorbent'],
    descriptors: {
      mw: 60.08,
      logP: 0.53,
      tpsa: 34.14,
      hbd: 0,
      hba: 2,
      heavyAtoms: 3,
      rotatableBonds: 0,
      fractionCsp3: 0.0,
      ringCount: 0,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Silica Oxide']
    },
    description: 'High surface area glidant and anti-tacking agent. Silanol surface groups can adsorb cationic basic drugs or hydrolyze moisture-sensitive actives.'
  },
  {
    id: 'exc-starch-maize',
    name: 'Maize Starch (Native)',
    casNumber: '9005-25-8',
    smiles: 'C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O',
    formula: '(C6H10O5)n',
    category: 'Diluent',
    typicalConcentration: '5 - 20% (Disintegrant), 10 - 50% (Binder/Diluent)',
    dosageForms: ['Tablet', 'Capsule'],
    reactiveRiskGroups: ['Carbohydrate Polymer', 'Absorbed Moisture (10-14%)'],
    descriptors: {
      mw: 342.3,
      logP: -3.8,
      tpsa: 179.3,
      hbd: 7,
      hba: 10,
      heavyAtoms: 23,
      rotatableBonds: 3,
      fractionCsp3: 1.0,
      ringCount: 2,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Amylose / Amylopectin']
    },
    description: 'Multi-functional diluent, binder, and disintegrant. Contains ~10-14% equilibrium moisture which may initiate hydrolysis in vulnerable drugs.'
  },
  {
    id: 'exc-sodium-starch-glycolate',
    name: 'Sodium Starch Glycolate (Explotab)',
    casNumber: '9063-38-1',
    smiles: 'C1C(C(C(C(O1)OCC(=O)[O-].[Na+])O)O)O',
    formula: '(C8H11NaO7)n',
    category: 'Disintegrant',
    typicalConcentration: '2 - 8%',
    dosageForms: ['Tablet', 'Capsule'],
    reactiveRiskGroups: ['Sodium Carboxymethyl Starch', 'Alkaline pH Microenvironment (pH 5.5-7.5)'],
    descriptors: {
      mw: 242.16,
      logP: -2.8,
      tpsa: 110.0,
      hbd: 3,
      hba: 7,
      heavyAtoms: 15,
      rotatableBonds: 3,
      fractionCsp3: 0.8,
      ringCount: 1,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Carboxymethyl Ether', 'Sodium Salt']
    },
    description: 'Rapid superdisintegrant operating by intense water absorption and cross-directional expansion.'
  },
  {
    id: 'exc-citric-acid',
    name: 'Citric Acid Anhydrous',
    casNumber: '77-92-9',
    smiles: 'C(C(=O)O)C(CC(=O)O)(C(=O)O)O',
    formula: 'C6H8O7',
    category: 'Buffer',
    typicalConcentration: '0.1 - 2%',
    dosageForms: ['Effervescent Tablet', 'Oral Liquid', 'Injectable Buffer'],
    reactiveRiskGroups: ['Tricarboxylic Acid', 'Acidic Microenvironment pH', 'Metal Chelator'],
    descriptors: {
      mw: 192.12,
      logP: -1.72,
      tpsa: 132.13,
      hbd: 4,
      hba: 7,
      heavyAtoms: 13,
      rotatableBonds: 4,
      fractionCsp3: 0.5,
      ringCount: 0,
      aromaticRings: 0,
      formalCharge: 0,
      functionalGroups: ['Tertiary Hydroxyl', 'Tricarboxylic Acid']
    },
    description: 'Acidifier and pH buffer. Strong acidic microenvironment can catalyze acid hydrolysis of labile esters and amides.'
  }
];
